### ISSUE TITLE
Any working example?

### ISSUE THREAD

**Issue by alperdincer** [rickj33/captureLeafletImage#1]
I know it is quite a new repo but is there any working example? :)

**Comment by rickj33** [comment]
The demo is testimage.html to get it to work, you will need to run npm install to install the required js files.

There is one issue and it is related to zoom animation. When animation is enabled, and the map is zoomed in/out or panned, then when I captured the image, the svg markers were not in the correct position. I did run across this article that may be related to the positioning. (Leaflet/Leaflet#3313) For our needs, we just turn off the animation on the map.
